bandeord = [
  {word: "Bærmeso", means: "fordrukken kvinde"},
  {word: "Douen las", means: "dovenlars, dalrerøv"},
  {word: "Drikke-bønnes", means: "en mand som kan drikke andre under bordet"},
  {word: "Fandens morgengave", means: "en led kvinde"},
  {word: "Dros", means: "dæmon eller djævel"},
  {word: "Bommerute", means: "fordrukken so"},
  {word: "Drukken-knægt", means: "fordrukken mand"},
  {word: "Generalhore", means: "en luder"},
  {word: "Dummerpande", means: "tosse"},
  {word: "Fjante", means: "idiot"},
  {word: "Lanke", means: "luder, hore"},
  {word: "Bardus", means: "en tosse som andre slår, driller og mishandler “,mobbeoffer”"},
  {word: "Fanting", means: "idiot"},
  {word: "Skidenso", means: "beskidt kvinde"},
  {word: "Kvindegek", means: "én der render efter kvinder,"},
  {word: "Drikke-so", means: "fordrukken kvinde"},
  {word: "Filke", means: "luder, usædelig kvinde"},
  {word: "Trippe", means: "kvinde som er usædelig i hemmelighed"},
  {word: "Horebuk", means: "liderlig mand"},
  {word: "Møddigtyr", means: "beskidt, siden dreng/karl"},
  {word: "Helvedes dørnagle", means: "ondsindet kvinde"},
  {word: "Fjove", means: "idiot, vanvittig, tosse"},
  {word: "Håndkone", means: "kvinde, som ligger i med en gift mand"},
  {word: "Bengær", means: "ond og modbydelig kvinde"},
  {word: "Bukkebede", means: "en kastreret ged"},
  {word: "Glom", means: "nar"},
  {word: "Kvindeskænder", means: "voldsmænd, bølle, voldtægtsmand"},
  {word: "Sokunte", means: "“svinefisse”"},
  {word: "Brændevinsmær", means: "fordrukken kvinde"},
  {word: "Sludøg", means: "“beskidte svin” (om kvinde)"},
  {word: "Dummerdos", means: "tossehoved, idiot"},
  {word: "Sute", means: "so, svin"},
  {word: "Ølsæk", means: "fordrukken mand/kvinde"},
  {word: "Skidenslatte", means: "beskidt kvinde"},
  {word: "Møgdyngetyr", means: "beskidt knægt"},
  {word: "Skandthore", means: "en (kagstrøgen og derfor uærlig) luder"}
]
