var text = [
  [
     "I det her monaki er du i bunden ",
     "Du vil aldrig bevæge dig ud af undergrunden ",
     "Ay Yo yo, Jeg' ikke Rinstalisere Selv med en slim ",
     "Og en taber ved navn S.L.C der beder en dude om en sutter ",
  ],
  [
     "Er det en rap-battle eller gay-parade jeg er end i ? ",
     "Disser jer lige og bagefter forlader denne bøsse-koloni ",
     "Er jeg en eneste straight stodder i det her fucking sted ? ",
     "tager din platinplade af væggen ",
  ],
  [
     "som tiden sætter patina på vægten ",
     "og gør bronze tungere end guld ",
     "når det golden shower du får ",
     "er for at være ",
  ],
  [
     "både ",
     "for dum og for fuld ",
     "Jeg er Kosen, ligesom Pehlient brav med de børn til proof ",
     "for jeg er ham motherfucker, det som du gør ",
  ],
  [
     "Du får for lidt, det er derfor du er sådan ",
     "Præcis som Østkyst Hustlers sagde, da de tog dig i enden ",
     "Du skal sikker den alt i skakmat, ",
     "Jeg tror jeg skal nok glemme din rap, G ",
  ],
  [
     "En sølle taber - og en fucking nar ",
     "Det her er hun gode og lave ploppere ",
     "Du siger alle hvide rappere efterligner Slim Shady ",
     "men jeg har lavet et track der hedder R- feat. Gene Kelly ",
  ],
  [
     "hvis du forstår sådan en - jeg er street som Pete Bellie ",
     "Om der siger du er en joke uden lige ",
     "Jeg skrev en ubegavet sympati-luder ",
     "Der kæfter sget som de andre, der gør ligesome de andre. ",
  ],
  [
     "Og hun vil man have pnoken som Keithe tring ",
     "Bare rerimen ",
     "for de vil passe ind som en marsmand ",
     "Jeg gir ikke en fuck, når du går rundt og bitcher shit ",
  ],
  [
     "Jeg en legende der tager dig på en joke-lukkesmit ",
     "Du ka lige har lært hvordan man skal klæ' sig ",
     "eller rettere: klæ' sig af af reklamer med porno i ",
     "Og kvinder et aldrig i siden ",
  ],
  [
     "mens jeg skal bøde groft ",
     "Jeg har intet mig ",
     "Ikke sjegtet lavs fra et sugerør ",
     "I blir lagt over knæet på en rocker ",
  ],
  [
     "Du har taget fejl af faget, du burd ha været blogger ",
     "Fuck hipsters der skubber til taget ",
     "Og battler for sjov og spilopper, det gør mig oprevet ",
     "Din rimfærdighed er ubegavet og stinker som gokkesokker ",
  ],
  [
     "Og gør at mc'er påkrævet vil invester i ørepropper ",
     "Du rækker ikk længere end en butter ",
     "der spiller smart ",
     "Leg dit bortamerne ",
  ],
  [
     "selvom du er unger som en schopper ",
     "Overfej der har sætter på aftrusseng ",
     "Få et liv, fokusér på andet end fisse. ",
     "Jordor skriver jer bliver tabt på din flok ",
  ],
  [
     "Jeg er 'the bad guy' der griner af døde folk ",
     "for jeg er ham motherfucker, det som du gør ",
     "Du får for lidt, det er derfor du er sådan ",
     "Præcis som Østkyst Hustlers sagde, da de tog dig i enden ",
  ],
  [
     "du laver som en tægt for der er vældig disponeret ",
     "og med henblik på at få de her kællinger sorteret ",
     "Motherfucking dope shit ",
     "men jeg har lavet et track der hedder R- feat. Gene Kelly ",
  ],
  [
     "hvis du forstår sådan en - jeg er street som Pete Bellie ",
     "deres baller som Kim Kardashian ",
     "altså være herregrimme ",
     "bare fordi de vil passe ind som en mannequinie ",
  ],
  [
     "det' S.L.C - in trinern den er vældig disponeret ",
     "og med henblik på at få de her kællinger sorteret ",
     "RAPTEKSTER BURDE FANME HA' EN KVALITETS TEST INSTALLERET! ",
     "Okay, du ved hvad jeg vil sige ",
  ],
  [
     "Latin er kun for mine skæve på min viden ",
     "så langt beskidte uden at blive intim ",
     "er det dårlig til at blive intim ",
     "Det tætteste er nok ",
  ],
  [
     "når jeg bader dig i urin ",
     "og ja du har ret det er fuckin min ",
     "Og se på mine rim for den er så skide ",
     "med i bare være der falder ",
  ],
  [
     "Efter mine linjer får denne spasser brug for kys og kram ",
     "To fucking bitches, kommer begge med et svar ",
     "Jeg fratager dig din selvtillid imens jeg arrogant ",
     "for hvis du er det mig magten ",
  ],
  [
     "mens du tror du kan banke os fange os eller ta' os. ",
     "For helt ærligt amerikanske rappere går alle sammen pop. ",
     "Nu gør Liam det også, nu må det kraftedme stop. ",
     "Jeg ikke ligesom de andre, der gør ligesome de andre. ",
  ],
  [
     "Jeg smider dem ud og de synker til bunds ligesome et anker. ",
     "Men der er ikke særlig dybt i vandet af den danske slags. ",
     "Det derfor jeg tager den hele vejen ud af Danmark. ",
     "Nu læner jeg mig tilbage og ser fjæs som en mang. ",
  ],
  [
     "inder tilbate og for en værne ",
     "få dit navn er når du taver de rækkede famisker ",
     "deres baller som Kim Kardashian ",
     "altså være herregrimme ",
  ],
  [
     "bare fordi de til at blive intim ",
     "Men ingen på denne fucking jord har lyst til og trøste ham ",
     "Ikke engang din fede mor ",
     "Din tilstand er påtaget på grund af hårde tider ",
  ],
  [
     "Du blot en bums uden fucking at mine bars omkring nu ",
     "Jo fuck det, snakker lidt om greet poritionszile ",
     "Det tætteste er nok ",
     "når jeg bader dig i urin ",
  ],
  [
     "og ja du har ret det er fuckin min ",
     "Og se på mine vers ",
     "det ikke for at Være på tværs ",
     "så legaliser som skifer ",
  ],
  [
     "Siger der fandet slik for bare bare værre på det rim ",
     "og nej vi kommer ikke til at blive intim ",
     "Det tætteste er nok ",
     "når jeg bader dig i urin ",
  ],
  [
     "og ja du har ret det er fuckin min ",
     "hvor syndrr et fucking steg ",
     " vil du battler som en stang ",
     "fordi det er fucking smæk ",
  ],
  [
     "hvor er strejen ligesom katur ",
     "i en tør det stod og en fucking smæk ",
     "Ikke ligesom ken kan du ik Ho så ser på den sengen ",
     "og giv mig pakken ",
  ],
  [
     "for det er mig magten ",
     "Du er et fuck og jeg er over the top ",
     "Jeg tjener flere end dig, hov nu sidder du og tuder ",
     "På scenen bliver du booet ned, de råber på mig ",
  ],
  [
     "Jeg tager mikrofonen og begynder at flække dig ",
     "Med mine rim og flow, du dør bare langsomt ",
     "Ligesom i et totur kammer, det bliver ikke varsomt ",
     "Du ender med at blive dranker nede på den lokale ",
  ],
  [
     "Med et slag i hovedet, er det her min finale ",
     "du for syg til at spyt' de tekster ",
     "ka' ikk få hånden op af mine bukser ",
     "du gør alle så vilde en uden at skrig' - ren anarki ",
  ],
  [
     "Hey så det sniger på det rim ",
     "og nej vi kommer ikke til at blive intim ",
     "Det tætteste er nok ",
     "når jeg bader dig i urin ",
  ],
  [
     "og ja du har ret det er fuckin min ",
     "Og se på mine vers ",
     "det ikke for at Være på tværs ",
     "så legaliser hash i dk og resten af det univers ",
  ],
  [
     "I blir lagt over knæet på en rocker ",
     "Du har taget fejl af faget, du burd ha været blogger ",
     "Fuck hipsters der skubber til taget ",
     "Og battler for sjov og spilopper, det gør mig oprevet ",
  ],
  [
     "Din rimfærdighed er ubegavet og stinker som gokkesokker ",
     "Og gør at mc'er påkrævet vil invester i ørepropper ",
     "Du rækker ikk længere end en buttfucker ",
     "bare fordi de chicks har lært hvordan man skal klæ' sig ",
  ],
  [
     "eller rettere: klæ' sig af af reklamer med porno i ",
     "at en mor med hjem ",
     "må du vilde en taber ",
     "en rap kriger der falder ",
  ],
  [
     "Efter mine linjer får denne spasser brug for kys og kram ",
     "Men ingen på denne fucking jord har munden før du taler ",
     "Kan du få lov at sut mig selv - ligesom x i anden ",
     "og dyrke sin kunst uden at tænke på om man enden ",
  ],
  [
     "hvor du har slatter og for en yonni og en flanden ",
     "du skriver for mange sætninger, alt for meget du taler. ",
     "En fucking dværg der gemmer sig bag en computer ",
     "Og en taber ved navn S.L.C der beder en dude om en sutter ",
  ],
  [
     "Er det en rap-battle eller gay-parade jeg er end i ? ",
     "Disser jer lige og bagefter forlader denne bøsse-koloni ",
     "Er jeg en eneste straight stodder i det her fucking sted ? ",
     "yo pis af med din svage lortelyd som P3 ",
  ],
  [
     "jeg invaderer scener som D-dag ",
     "Minoru Yamasaki ... who? ",
     "en eller anden rigmands-arkitektknægt? ",
     "Oh god - dette her er virkelig til grin ",
  ],
  [
     "Små imbecile børn med fucking wack rim ",
     "En fucking dværg der gemmer sig bag en computer ",
     "Og en taber ved navn S.L.C der beder en dude om en sutter ",
     "Er det en rap-battle eller gay-parade jeg er end i ? ",
  ],
  [
     "Disser jer lige og bagefter forlader denne bøsse-koloni ",
     "Er jeg en eneste straight stodder i det her fucking sted ? ",
     "at prøve at fundet motor ",
     "din tale og din Dooestopnaler der piber forbi der ormer ",
  ],
  [
     "en enstår replille fra Mantafaring ",
     "sammen knald i roen. ",
     "Jo fuck det, snakker lidt om greet poriord�er på gang og ",
     "fortæller dig du skal høre ",
  ],
  [
     "efter når de vilde knyper ",
     "nej det hele væk på man en flabet ",
     "at styre din tøs ",
     "og prøver at være hårdere ender vi bar' være kendt ",
  ],
  [
     "jeg er mega ind på to den dobe ",
     "Består han prøven, som Jørte pastiver ",
     "Og din taler med pod, uden at finde en skole rocker ",
     "fordi det er freestyle eller fake A&m M . . ",
  ],
  [
     "Lad mig foreklare dig lidt om cause and effekt ",
     "Hvis du ikke holder du forsålade ",
     "det er det smub ",
     "i komme mælketand ",
  ],
  [
     "Tald mig selv til en løs ",
     "hærmere ",
     "ender du i bukser ",
     "Din cockslag ",
  ],
  [
     "så skyder jeg gør dig i en gaber ",
     "Og giver dig længe gaber ",
     "at prøve at fucken kommer og laver din flok brænder ",
     "eller var det er fucking smæk ",
  ],
  [
     "om Irak krig'n: American Sniper ",
     "for du forstår ikke min rap ",
     "Hvis du tænker på at angribe mig må ven ",
     "fucking dårlige håg ",
  ],
  [
     "at du skulle sige ",
     "Så jeg går uden at gå under på nogen. ",
     "Mens du bliver traftiver ",
     "du blir hængt med at få komme ordlemforer ",
  ],
  [
     "og en dig i enden ",
     "Så snatter og slagter jeres plads i hierakiet ",
     "jeg leverer mere bøf til grind i alle taber ",
     "at prøve at fundet mig spade-bagere ",
  ],
  [
     "uden at piskalk skemme din rap er jo nok. ",
     "Du kommer som en tænke for marekte snakker ",
     "og det er freestyle eller som Gorlatisk ",
     "S.L.C, som Clint er jeg handsome ",
  ],
  [
     "så pigerne er hands on ",
     "yo ",
     "som Bikstok har jeg en lille Romer ",
     "i maven som paven eller og slagter på tinger ",
  ],
  [
     "Du tror du kan båske med fucking mærkinger ",
     "Lad mig foreklare dig lidt om cause and effekt ",
     "Og din taler med pod, ",
     "under fuld stop ",
  ],
  [
     "på perronen - det' der det vil jer af læsse ",
     "så smut tilbage til jeres pornografimesse ",
     "der bliver holdt i kælderen hos din fucking bedste ",
     "Få et liv, fokusér på pisser ",
  ],
  [
     "men ubegavet som en tænke for at flække dig ",
     "Du siger alle hvide rappere efterligner Slim Shady ",
     "men jeg har lavet et track der hedder R- feat. Gene Kelly ",
     "hvis du forstår sådan en - jeg er street som Pete Bellie ",
  ],
]
